version: '3.8'

services:
  app:
    build: .
    container_name: uidai_risk_engine
    ports:
      - "8000:8000"
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - PORT=8000
      - HOST=0.0.0.0
      - DEBUG=False
    restart: unless-stopped
